# Generated by Django 5.1.4 on 2025-01-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned by Tanim'),)},
        ),
    ]
