# Generated by Django 5.1.4 on 2025-01-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalLibrary', '0002_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Mark book returned'),)},
        ),
    ]
