# Generated by Django 5.1.4 on 2025-01-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalLibrary', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_add_author', 'Add Author'), ('can_change_author', 'Change Author'), ('can_delete_author', 'Delete Author'))},
        ),
    ]
