# Generated by Django 5.1.4 on 2025-01-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalLibrary', '0004_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_add_book', 'Add Book'), ('can_edit_book', 'Change Book'), ('can_delete_book', 'Delete Book'))},
        ),
    ]
